env: 'dev'
appName: 'community'
http:
  host: '0.0.0.0'
  port: 3002
db:
  mongo:
    url: 'mongodb://localhost:27017/one_gridfs'
    retry:
      attempts: 0
      delay: 500
  postgres:
    url: "postgresql://localhost:15432/ong?stringtype=unspecified"
    user: "web-education"
    password: "We_1234"
    debug: false
    schema: "community"
nats:
  url: 'nats://localhost:4222'
  debug: true
temporal:
  address: 'localhost:7233'
  namespace: 'default'
log:
  level: 'debug'
swagger:
  title: '@edifice.io/community-backend'
  description: 'API description of community backend'